version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - custom_network
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - custom_network
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - custom_network
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
